const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_1001',
  AUTH_INVALID_TOKEN: 'AUTH_1002',
  AUTH_TOKEN_EXPIRED: 'AUTH_1003',
  AUTH_INVALID_CREDENTIALS: 'AUTH_1004',

  VALIDATION_FAILED: 'VAL_2001',
  VALIDATION_MISSING_FIELD: 'VAL_2002',
  VALIDATION_INVALID_FORMAT: 'VAL_2003',

  RESOURCE_NOT_FOUND: 'RES_3001',
  RESOURCE_ALREADY_EXISTS: 'RES_3002',
  RESOURCE_ACCESS_DENIED: 'RES_3003',

  INTERNAL_SERVER_ERROR: 'SRV_5001',
  DATABASE_ERROR: 'SRV_5002',
  EXTERNAL_SERVICE_ERROR: 'SRV_5003'
};

module.exports = ERROR_CODES;
